### ISSUE TITLE
Unlimited parts once purchased and relogging it will go 0% and can't fix them

### ISSUE THREAD

**Issue by hyk333** [SoWeBegin/MicrovoltsEmulator#19]
Unlimited parts once purchased and relogging it will go 0% and can't fix them
![imagem_2024-09-27_183920262](https://github.com/user-attachments/assets/8e9e4b1c-6493-48d6-82b6-7a8421a9accd)

**Comment by SoWeBegin** [comment]
Thanks!
This should be fixed with the latest commit: 195dbc4e1e7034d95f60c91b690c7e0c25054401
